baseURL = 'https://chanfulmer.com/'
languageCode = 'en-us'
title = 'chanfulmer dot com'
theme = 'dark-minimal'

# Menu is defined manually below

[params]
authorName = "Chandler Fulmer"
description = "Chan's Blog"
aboutMe = "I'm Chandler, this is a collection of projects, writing, reading, and software. I wanted a place to publish niche tech issues I ran into, or opinions on the state of the world, just in case it was interesting to any passerby on the web."
# Social media handles
github = "herboh"
twitter = "yourusername"
linkedin = "yourusername"

# Navigation menu
[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1
[[menu.main]]
name = "CV"
url = "/cv/"
weight = 2
[[menu.main]]
name = "Books"
url = "/books/"
weight = 3
[[menu.main]]
name = "Giki"
url = "/wiki/"
weight = 4

[module]
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "wiki/content"
    target = "static/wiki"
