baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'chanfulmer dot com'
theme = 'dark-minimal'

# Menu is defined manually below

[params]
  authorName = "Chandler Fulmer"
  description = "Personal site of Chandler Fulmer"
  aboutMe = "Hi, I'm Chandler Fulmer. I'm a software engineer and technology enthusiast. This is where I share my thoughts on programming, books I've read, and other interesting topics."
  # Social media handles
  github = "herboh"
  twitter = "yourusername"
  linkedin = "yourusername"

# Navigation menu
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 3
