baseURL = 'https://chanfulmer.com/'
locale = 'en-US'
title = 'chanfulmer dot com'
theme = 'dark-minimal'
summaryLength = 32
enableRobotsTXT = true

[params]
authorName = "Chandler Fulmer"
description = "Software, Linux, books, and side projects."
tagline = "Software, Linux, books, and side projects."
homeStatus = "Static, fast, and under active maintenance again."
aboutMe = "I'm Chandler, this is a collection of projects, writing, reading, and software. I wanted a place to publish niche tech issues I ran into, or opinions on the state of the world, just in case it was interesting to any passerby on the web."
github = "herboh"

[menu]
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 1
[[menu.main]]
name = "CV"
url = "/cv/"
weight = 2
[[menu.main]]
name = "Books"
url = "/books/"
weight = 3

[[menu.main]]
name = "Interests"
url = "/interests/"
weight = 4

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "gruvbox"
    lineNos = false
    noClasses = true
    guessSyntax = true
